export const fonts = {
  sans: "'Roboto Flex', 'Noto Sans', 'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif",
  mono: "'Roboto Mono', 'JetBrains Mono', 'Fira Code', 'SFMono-Regular', 'Source Code Pro', monospace",
  display: "'Google Sans Display', 'Roboto Flex', 'Segoe UI', system-ui, sans-serif"
} as const

export const spacing = {
  xxs: '0.25rem',
  xs: '0.5rem',
  sm: '0.75rem',
  md: '1rem',
  lg: '1.5rem',
  xl: '2rem',
  xxl: '2.5rem',
  xxxl: '3.5rem'
} as const

export const typography = {
  display: {
    large: { size: '3.5625rem', lineHeight: '4rem', tracking: '-0.015em', weight: 400 },
    medium: { size: '2.8125rem', lineHeight: '3.25rem', tracking: '0em', weight: 400 },
    small: { size: '2.25rem', lineHeight: '2.75rem', tracking: '0em', weight: 400 }
  },
  headline: {
    large: { size: '2rem', lineHeight: '2.5rem', tracking: '0em', weight: 400 },
    medium: { size: '1.75rem', lineHeight: '2.25rem', tracking: '0em', weight: 400 },
    small: { size: '1.5rem', lineHeight: '2rem', tracking: '0em', weight: 400 }
  },
  title: {
    large: { size: '1.375rem', lineHeight: '1.75rem', tracking: '0em', weight: 600 },
    medium: { size: '1.125rem', lineHeight: '1.5rem', tracking: '0.01em', weight: 600 },
    small: { size: '1rem', lineHeight: '1.4rem', tracking: '0.01em', weight: 600 }
  },
  body: {
    large: { size: '1rem', lineHeight: '1.6rem', tracking: '0.01em', weight: 400 },
    medium: { size: '0.875rem', lineHeight: '1.45rem', tracking: '0.015em', weight: 400 },
    small: { size: '0.75rem', lineHeight: '1.3rem', tracking: '0.02em', weight: 400 }
  },
  label: {
    large: { size: '0.875rem', lineHeight: '1.25rem', tracking: '0.01em', weight: 600 },
    medium: { size: '0.75rem', lineHeight: '1rem', tracking: '0.04em', weight: 600 },
    small: { size: '0.6875rem', lineHeight: '1rem', tracking: '0.08em', weight: 600 }
  }
} as const

export const radii = {
  xs: '0.25rem',
  sm: '0.5rem',
  md: '0.75rem',
  lg: '1rem',
  xl: '1.5rem',
  pill: '999px'
} as const

export const shadows = {
  level1: '0 1px 2px rgba(15, 23, 42, 0.08), 0 1px 3px rgba(15, 23, 42, 0.06)',
  level2: '0 4px 8px rgba(15, 23, 42, 0.1), 0 2px 6px rgba(15, 23, 42, 0.06)',
  level3: '0 8px 16px rgba(15, 23, 42, 0.12), 0 6px 10px rgba(15, 23, 42, 0.08)',
  level4: '0 12px 20px rgba(15, 23, 42, 0.14), 0 6px 12px rgba(15, 23, 42, 0.08)',
  level5: '0 20px 32px rgba(15, 23, 42, 0.18), 0 12px 24px rgba(15, 23, 42, 0.1)'
} as const

export const motion = {
  durations: {
    xs: '120ms',
    sm: '160ms',
    md: '220ms',
    lg: '320ms',
    xl: '480ms'
  },
  delays: {
    sm: '45ms',
    md: '90ms'
  },
  easings: {
    standard: 'cubic-bezier(0.2, 0, 0, 1)',
    decelerate: 'cubic-bezier(0, 0, 0.2, 1)',
    accelerate: 'cubic-bezier(0.4, 0, 1, 1)',
    emphasized: 'cubic-bezier(0.05, 0.7, 0.1, 1)',
    emphasizedDecelerate: 'cubic-bezier(0.05, 0.7, 0.1, 1)',
    emphasizedAccelerate: 'cubic-bezier(0.3, 0, 0.8, 0.15)'
  }
} as const

export const transitions = {
  micro: `${motion.durations.xs} ${motion.easings.emphasizedDecelerate}`,
  short: `${motion.durations.sm} ${motion.easings.standard}`,
  medium: `${motion.durations.md} ${motion.easings.standard}`,
  long: `${motion.durations.lg} ${motion.easings.standard}`,
  emphasized: `${motion.durations.md} ${motion.easings.emphasized}`
} as const

export const stateLayers = {
  hover: 0.08,
  focus: 0.12,
  pressed: 0.12,
  dragged: 0.16
} as const

type ThemeVariableRecord = Record<string, string>

const materialAuroraVars = {
  '--font-sans': "'Roboto Flex', 'Noto Sans', 'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif",
  '--font-display': "'Google Sans Display', 'Roboto Flex', 'Segoe UI', system-ui, sans-serif",
  '--font-mono': "'Roboto Mono', 'JetBrains Mono', 'Fira Code', 'SFMono-Regular', 'Source Code Pro', monospace",

  '--space-xxs': spacing.xxs,
  '--space-xs': spacing.xs,
  '--space-sm': spacing.sm,
  '--space-md': spacing.md,
  '--space-lg': spacing.lg,
  '--space-xl': spacing.xl,
  '--space-2xl': spacing.xxl,
  '--space-3xl': spacing.xxxl,

  '--radius-xs': radii.xs,
  '--radius-sm': radii.sm,
  '--radius-md': '0.9rem',
  '--radius-lg': '1.35rem',
  '--radius-xl': '1.9rem',
  '--radius-pill': radii.pill,

  '--shadow-level1': '0 16px 32px rgba(103, 80, 164, 0.12)',
  '--shadow-level2': '0 28px 56px rgba(103, 80, 164, 0.18)',
  '--shadow-level3': '0 36px 64px rgba(73, 49, 122, 0.2)',
  '--shadow-level4': '0 48px 82px rgba(73, 49, 122, 0.26)',
  '--shadow-level5': '0 60px 96px rgba(73, 49, 122, 0.3)',
  '--shadow-elevated': '0 32px 60px rgba(103, 80, 164, 0.16)',

  '--motion-duration-xs': motion.durations.xs,
  '--motion-duration-sm': motion.durations.sm,
  '--motion-duration-md': motion.durations.md,
  '--motion-duration-lg': motion.durations.lg,
  '--motion-duration-xl': motion.durations.xl,
  '--motion-delay-sm': motion.delays.sm,
  '--motion-delay-md': motion.delays.md,
  '--motion-easing-standard': motion.easings.standard,
  '--motion-easing-decelerate': motion.easings.decelerate,
  '--motion-easing-accelerate': motion.easings.accelerate,
  '--motion-easing-emphasized': motion.easings.emphasized,
  '--motion-easing-emphasized-decelerate': motion.easings.emphasizedDecelerate,
  '--motion-easing-emphasized-accelerate': motion.easings.emphasizedAccelerate,

  '--transition-micro': transitions.micro,
  '--transition-short': transitions.short,
  '--transition-medium': transitions.medium,
  '--transition-long': transitions.long,
  '--transition-emphasized': transitions.emphasized,

  '--md-comp-state-layer-opacity-hover': String(stateLayers.hover),
  '--md-comp-state-layer-opacity-focus': String(stateLayers.focus),
  '--md-comp-state-layer-opacity-pressed': String(stateLayers.pressed),

  '--md-sys-color-primary': '#6750A4',
  '--md-sys-color-on-primary': '#FFFFFF',
  '--md-sys-color-primary-container': '#EADDFF',
  '--md-sys-color-on-primary-container': '#21005D',
  '--md-sys-color-secondary': '#625B71',
  '--md-sys-color-on-secondary': '#FFFFFF',
  '--md-sys-color-secondary-container': '#E8DEF8',
  '--md-sys-color-on-secondary-container': '#1D192B',
  '--md-sys-color-tertiary': '#7D5260',
  '--md-sys-color-on-tertiary': '#FFFFFF',
  '--md-sys-color-tertiary-container': '#FFD8E4',
  '--md-sys-color-on-tertiary-container': '#31111D',
  '--md-sys-color-background': '#FFFBFE',
  '--md-sys-color-on-background': '#1C1B1F',
  '--md-sys-color-surface': '#FFFBFE',
  '--md-sys-color-on-surface': '#1C1B1F',
  '--md-sys-color-surface-variant': '#E7E0EC',
  '--md-sys-color-on-surface-variant': '#49454F',
  '--md-sys-color-outline': '#79747E',
  '--md-sys-color-outline-variant': '#CAC4D0',
  '--md-sys-color-shadow': '#000000',
  '--md-sys-color-scrim': '#000000',
  '--md-sys-color-surface-tint': '#6750A4',
  '--md-sys-color-inverse-surface': '#313033',
  '--md-sys-color-inverse-on-surface': '#F4EFF4',
  '--md-sys-color-inverse-primary': '#D0BCFF',
  '--md-sys-color-surface-container-lowest': '#FFFFFF',
  '--md-sys-color-surface-container-low': '#F7F2FA',
  '--md-sys-color-surface-container': '#F3EDF7',
  '--md-sys-color-surface-container-high': '#ECE6F0',
  '--md-sys-color-surface-container-highest': '#E6E0E9',
  '--md-sys-color-error': '#B3261E',
  '--md-sys-color-on-error': '#FFFFFF',
  '--md-sys-color-error-container': '#F9DEDC',
  '--md-sys-color-on-error-container': '#410E0B',
  '--md-sys-color-success': '#2E7D32',
  '--md-sys-color-on-success': '#FFFFFF',
  '--md-sys-color-success-container': '#C8E6C9',
  '--md-sys-color-on-success-container': '#0F3813',

  '--bg': '#F7F2FA',
  '--fg': '#1C1B1F',
  '--muted': '#625B71',
  '--link': '#6750A4',
  '--surface': '#FFFBFE',
  '--surface-2': '#F3EDF7',
  '--surface-panel': '#ECE6F0',
  '--surface-veil': 'rgba(103, 80, 164, 0.08)',
  '--surface-translucent': 'rgba(255, 255, 255, 0.85)',
  '--border': 'rgba(103, 80, 164, 0.18)',
  '--border-soft': 'rgba(103, 80, 164, 0.12)',
  '--border-muted': 'rgba(103, 80, 164, 0.08)',
  '--border-strong': '#79747E',
  '--accent': '#6750A4',
  '--accent-weak': '#EADDFF',
  '--accent-strong': '#21005D',
  '--enemy-accent': '#B3261E',
  '--env-accent': '#2F6F3D',
  '--danger-soft': 'rgba(179, 38, 30, 0.16)',
  '--success-soft': 'rgba(46, 125, 50, 0.16)',
  '--danger-border': 'rgba(179, 38, 30, 0.3)',
  '--success-border': 'rgba(46, 125, 50, 0.3)',
  '--overlay': 'rgba(15, 12, 40, 0.16)',
  '--gridline': 'rgba(103, 80, 164, 0.08)',

  '--md-comp-button-filled-container': 'var(--md-sys-color-primary)',
  '--md-comp-button-filled-on-container': 'var(--md-sys-color-on-primary)',
  '--md-comp-button-filled-container-hover': "color-mix(in srgb, var(--md-comp-button-filled-container) 92%, var(--md-sys-color-on-primary) 8%)",
  '--md-comp-button-tonal-container': 'var(--md-sys-color-secondary-container)',
  '--md-comp-button-tonal-on-container': 'var(--md-sys-color-on-secondary-container)',
  '--md-comp-button-tonal-container-hover': "color-mix(in srgb, var(--md-comp-button-tonal-container) 90%, var(--md-sys-color-on-secondary-container) 10%)",
  '--md-comp-button-elevated-container': 'var(--md-sys-color-surface-container-high)',
  '--md-comp-button-elevated-on-container': 'var(--md-sys-color-on-surface)',
  '--md-comp-button-elevated-container-hover': "color-mix(in srgb, var(--md-comp-button-elevated-container) 92%, var(--md-sys-color-surface-tint) 8%)",
  '--md-comp-button-outlined-outline': 'var(--md-sys-color-outline)',
  '--md-comp-button-outlined-hover-layer': "color-mix(in srgb, var(--md-comp-button-text-label) 12%, transparent)",
  '--md-comp-button-text-label': 'var(--md-sys-color-primary)',
  '--md-comp-button-text-hover-layer': "color-mix(in srgb, var(--md-comp-button-text-label) 12%, transparent)",
  '--md-comp-button-ghost-label': 'var(--md-sys-color-on-surface-variant)',
  '--md-comp-button-ghost-hover-layer': "color-mix(in srgb, var(--md-comp-button-ghost-label) 10%, transparent)",
  '--md-comp-button-danger-container': 'var(--md-sys-color-error)',
  '--md-comp-button-danger-on-container': 'var(--md-sys-color-on-error)',
  '--md-comp-button-danger-container-hover': "color-mix(in srgb, var(--md-comp-button-danger-container) 92%, var(--md-sys-color-on-error) 8%)",
  '--md-comp-button-success-container': 'var(--md-sys-color-success)',
  '--md-comp-button-success-on-container': 'var(--md-sys-color-on-success)',
  '--md-comp-button-success-container-hover': "color-mix(in srgb, var(--md-comp-button-success-container) 92%, var(--md-sys-color-on-success) 8%)",
  '--md-comp-focus-ring': 'var(--md-sys-color-primary)',

  '--md-comp-field-container': "color-mix(in srgb, var(--md-sys-color-surface) 92%, var(--md-sys-color-surface-variant) 8%)",
  '--md-comp-field-outline': "color-mix(in srgb, var(--md-sys-color-outline) 55%, transparent)",
  '--md-comp-field-on-surface': 'var(--md-sys-color-on-surface)',
  '--md-comp-field-placeholder': 'var(--md-sys-color-on-surface-variant)'
} as const satisfies ThemeVariableRecord

const materialMidnightVars = {
  ...materialAuroraVars,
  '--font-sans': "'Roboto Flex', 'Noto Sans', 'Inter', 'Segoe UI', system-ui, -apple-system, sans-serif",
  '--md-sys-color-primary': '#D0BCFF',
  '--md-sys-color-on-primary': '#381E72',
  '--md-sys-color-primary-container': '#4F378B',
  '--md-sys-color-on-primary-container': '#EADDFF',
  '--md-sys-color-secondary': '#CCC2DC',
  '--md-sys-color-on-secondary': '#332D41',
  '--md-sys-color-secondary-container': '#4A4458',
  '--md-sys-color-on-secondary-container': '#E8DEF8',
  '--md-sys-color-tertiary': '#EFB8C8',
  '--md-sys-color-on-tertiary': '#492532',
  '--md-sys-color-tertiary-container': '#633B48',
  '--md-sys-color-on-tertiary-container': '#FFD8E4',
  '--md-sys-color-background': '#1C1B1F',
  '--md-sys-color-on-background': '#E6E1E5',
  '--md-sys-color-surface': '#1C1B1F',
  '--md-sys-color-on-surface': '#E6E1E5',
  '--md-sys-color-surface-variant': '#49454F',
  '--md-sys-color-on-surface-variant': '#CAC4D0',
  '--md-sys-color-outline': '#938F99',
  '--md-sys-color-outline-variant': '#49454F',
  '--md-sys-color-surface-tint': '#D0BCFF',
  '--md-sys-color-inverse-surface': '#E6E1E5',
  '--md-sys-color-inverse-on-surface': '#313033',
  '--md-sys-color-inverse-primary': '#6750A4',
  '--md-sys-color-surface-container-lowest': '#0F0D13',
  '--md-sys-color-surface-container-low': '#1D1B20',
  '--md-sys-color-surface-container': '#211F26',
  '--md-sys-color-surface-container-high': '#2B2930',
  '--md-sys-color-surface-container-highest': '#36343B',
  '--md-sys-color-error': '#F2B8B5',
  '--md-sys-color-on-error': '#601410',
  '--md-sys-color-error-container': '#8C1D18',
  '--md-sys-color-on-error-container': '#F9DEDC',
  '--md-sys-color-success': '#8EDFA5',
  '--md-sys-color-on-success': '#003915',
  '--md-sys-color-success-container': '#135727',
  '--md-sys-color-on-success-container': '#BEECC6',

  '--bg': '#141218',
  '--fg': '#E6E1E5',
  '--muted': '#CAC4D0',
  '--link': '#D0BCFF',
  '--surface': '#1D1B20',
  '--surface-2': '#211F26',
  '--surface-panel': '#2B2930',
  '--surface-veil': 'rgba(208, 188, 255, 0.12)',
  '--surface-translucent': 'rgba(29, 27, 32, 0.78)',
  '--border': 'rgba(208, 188, 255, 0.24)',
  '--border-soft': 'rgba(208, 188, 255, 0.18)',
  '--border-muted': 'rgba(208, 188, 255, 0.12)',
  '--border-strong': '#938F99',
  '--accent': '#D0BCFF',
  '--accent-weak': 'rgba(208, 188, 255, 0.24)',
  '--accent-strong': '#381E72',
  '--enemy-accent': '#FFB4AB',
  '--env-accent': '#8CDC90',
  '--danger-soft': 'rgba(242, 184, 181, 0.16)',
  '--success-soft': 'rgba(142, 223, 165, 0.18)',
  '--danger-border': 'rgba(242, 184, 181, 0.4)',
  '--success-border': 'rgba(142, 223, 165, 0.42)',
  '--overlay': 'rgba(4, 0, 20, 0.42)',
  '--gridline': 'rgba(208, 188, 255, 0.08)',

  '--shadow-level1': '0 18px 34px rgba(3, 0, 24, 0.38)',
  '--shadow-level2': '0 28px 52px rgba(3, 0, 24, 0.46)',
  '--shadow-level3': '0 36px 70px rgba(3, 0, 24, 0.56)',
  '--shadow-level4': '0 48px 82px rgba(3, 0, 24, 0.62)',
  '--shadow-level5': '0 64px 102px rgba(3, 0, 24, 0.7)',
  '--shadow-elevated': '0 32px 60px rgba(3, 0, 24, 0.48)',

  '--md-comp-button-text-label': '#D0BCFF',
  '--md-comp-button-ghost-label': '#CAC4D0',
  '--md-comp-button-text-hover-layer': "color-mix(in srgb, #D0BCFF 16%, transparent)",
  '--md-comp-button-ghost-hover-layer': "color-mix(in srgb, #CAC4D0 16%, transparent)",
  '--md-comp-button-outlined-outline': 'color-mix(in srgb, #CAC4D0 60%, transparent)',
  '--md-comp-button-outlined-hover-layer': "color-mix(in srgb, #D0BCFF 18%, transparent)",
  '--md-comp-button-elevated-container': 'color-mix(in srgb, var(--md-sys-color-surface) 92%, rgba(208, 188, 255, 0.14) 8%)',
  '--md-comp-button-elevated-on-container': 'var(--md-sys-color-on-surface)',
  '--md-comp-button-elevated-container-hover': "color-mix(in srgb, var(--md-comp-button-elevated-container) 90%, rgba(208, 188, 255, 0.2) 10%)",
  '--md-comp-focus-ring': '#D0BCFF',

  '--md-comp-field-container': "color-mix(in srgb, var(--md-sys-color-surface) 86%, rgba(208, 188, 255, 0.22) 14%)",
  '--md-comp-field-outline': "color-mix(in srgb, #938F99 55%, transparent)",
  '--md-comp-field-on-surface': 'var(--md-sys-color-on-surface)',
  '--md-comp-field-placeholder': 'var(--md-sys-color-on-surface-variant)'
} as const satisfies ThemeVariableRecord

const appleSkyVars = {
  '--font-sans': "'SF Pro Text', 'SF Pro Display', 'Inter', 'Helvetica Neue', 'Arial', sans-serif",
  '--font-display': "'SF Pro Display', 'SF Pro Rounded', 'Inter', 'Helvetica Neue', 'Arial', sans-serif",
  '--font-mono': materialAuroraVars['--font-mono'],

  '--space-xxs': spacing.xxs,
  '--space-xs': spacing.xs,
  '--space-sm': spacing.sm,
  '--space-md': spacing.md,
  '--space-lg': spacing.lg,
  '--space-xl': spacing.xl,
  '--space-2xl': spacing.xxl,
  '--space-3xl': spacing.xxxl,

  '--radius-xs': '0.3rem',
  '--radius-sm': '0.45rem',
  '--radius-md': '0.8rem',
  '--radius-lg': '1.1rem',
  '--radius-xl': '1.6rem',
  '--radius-pill': radii.pill,

  '--shadow-level1': '0 14px 28px rgba(15, 15, 20, 0.12)',
  '--shadow-level2': '0 22px 44px rgba(15, 15, 20, 0.14)',
  '--shadow-level3': '0 32px 56px rgba(15, 15, 20, 0.16)',
  '--shadow-level4': '0 42px 72px rgba(15, 15, 20, 0.18)',
  '--shadow-level5': '0 56px 96px rgba(15, 15, 20, 0.22)',
  '--shadow-elevated': '0 28px 48px rgba(15, 15, 20, 0.12)',

  '--motion-duration-xs': motion.durations.xs,
  '--motion-duration-sm': motion.durations.sm,
  '--motion-duration-md': motion.durations.md,
  '--motion-duration-lg': motion.durations.lg,
  '--motion-duration-xl': motion.durations.xl,
  '--motion-delay-sm': motion.delays.sm,
  '--motion-delay-md': motion.delays.md,
  '--motion-easing-standard': 'cubic-bezier(0.23, 1, 0.32, 1)',
  '--motion-easing-decelerate': 'cubic-bezier(0.16, 1, 0.3, 1)',
  '--motion-easing-accelerate': 'cubic-bezier(0.7, 0, 0.84, 0)',
  '--motion-easing-emphasized': 'cubic-bezier(0.2, 0, 0, 1)',
  '--motion-easing-emphasized-decelerate': 'cubic-bezier(0.2, 0.8, 0.2, 1)',
  '--motion-easing-emphasized-accelerate': 'cubic-bezier(0.3, 0, 0.7, 0.1)',

  '--transition-micro': `${motion.durations.xs} cubic-bezier(0.2, 0, 0, 1)`,
  '--transition-short': `${motion.durations.sm} cubic-bezier(0.23, 1, 0.32, 1)`,
  '--transition-medium': `${motion.durations.md} cubic-bezier(0.23, 1, 0.32, 1)`,
  '--transition-long': `${motion.durations.lg} cubic-bezier(0.23, 1, 0.32, 1)`,
  '--transition-emphasized': `${motion.durations.md} cubic-bezier(0.2, 0, 0, 1)`,

  '--md-comp-state-layer-opacity-hover': '0.06',
  '--md-comp-state-layer-opacity-focus': '0.1',
  '--md-comp-state-layer-opacity-pressed': '0.12',

  '--md-sys-color-primary': '#0A84FF',
  '--md-sys-color-on-primary': '#FFFFFF',
  '--md-sys-color-primary-container': '#DDEBFF',
  '--md-sys-color-on-primary-container': '#00264D',
  '--md-sys-color-secondary': '#5E5CE6',
  '--md-sys-color-on-secondary': '#FFFFFF',
  '--md-sys-color-secondary-container': '#E4E3FF',
  '--md-sys-color-on-secondary-container': '#1D1A8B',
  '--md-sys-color-tertiary': '#30D158',
  '--md-sys-color-on-tertiary': '#003A10',
  '--md-sys-color-tertiary-container': '#C8F8D1',
  '--md-sys-color-on-tertiary-container': '#00270A',
  '--md-sys-color-background': '#F5F5F7',
  '--md-sys-color-on-background': '#1D1D1F',
  '--md-sys-color-surface': '#FFFFFF',
  '--md-sys-color-on-surface': '#1D1D1F',
  '--md-sys-color-surface-variant': 'rgba(60, 60, 67, 0.12)',
  '--md-sys-color-on-surface-variant': 'rgba(60, 60, 67, 0.72)',
  '--md-sys-color-outline': 'rgba(60, 60, 67, 0.36)',
  '--md-sys-color-outline-variant': 'rgba(60, 60, 67, 0.2)',
  '--md-sys-color-shadow': 'rgba(15, 15, 20, 0.5)',
  '--md-sys-color-scrim': 'rgba(10, 10, 10, 0.6)',
  '--md-sys-color-surface-tint': '#0A84FF',
  '--md-sys-color-inverse-surface': '#1D1D1F',
  '--md-sys-color-inverse-on-surface': '#F5F5F7',
  '--md-sys-color-inverse-primary': '#66B7FF',
  '--md-sys-color-surface-container-lowest': '#FFFFFF',
  '--md-sys-color-surface-container-low': '#F5F5F7',
  '--md-sys-color-surface-container': '#EFF0F6',
  '--md-sys-color-surface-container-high': '#E5E6ED',
  '--md-sys-color-surface-container-highest': '#DADBE3',
  '--md-sys-color-error': '#FF3B30',
  '--md-sys-color-on-error': '#FFFFFF',
  '--md-sys-color-error-container': '#FFDAD3',
  '--md-sys-color-on-error-container': '#5A000B',
  '--md-sys-color-success': '#34C759',
  '--md-sys-color-on-success': '#002D0E',
  '--md-sys-color-success-container': '#C9F7D3',
  '--md-sys-color-on-success-container': '#003916',

  '--bg': '#F5F5F7',
  '--fg': '#1D1D1F',
  '--muted': 'rgba(60, 60, 67, 0.72)',
  '--link': '#0A84FF',
  '--surface': '#FFFFFF',
  '--surface-2': '#EFF0F6',
  '--surface-panel': '#E5E6ED',
  '--surface-veil': 'rgba(10, 132, 255, 0.08)',
  '--surface-translucent': 'rgba(255, 255, 255, 0.82)',
  '--border': 'rgba(60, 60, 67, 0.18)',
  '--border-soft': 'rgba(60, 60, 67, 0.12)',
  '--border-muted': 'rgba(60, 60, 67, 0.08)',
  '--border-strong': 'rgba(60, 60, 67, 0.28)',
  '--accent': '#0A84FF',
  '--accent-weak': 'rgba(10, 132, 255, 0.22)',
  '--accent-strong': '#003A73',
  '--enemy-accent': '#FF375F',
  '--env-accent': '#30D158',
  '--danger-soft': 'rgba(255, 59, 48, 0.16)',
  '--success-soft': 'rgba(52, 199, 89, 0.16)',
  '--danger-border': 'rgba(255, 59, 48, 0.24)',
  '--success-border': 'rgba(52, 199, 89, 0.24)',
  '--overlay': 'rgba(25, 25, 35, 0.2)',
  '--gridline': 'rgba(60, 60, 67, 0.12)',

  '--md-comp-button-filled-container': 'var(--accent)',
  '--md-comp-button-filled-on-container': '#FFFFFF',
  '--md-comp-button-filled-container-hover': "color-mix(in srgb, var(--accent) 92%, #FFFFFF 8%)",
  '--md-comp-button-tonal-container': "color-mix(in srgb, var(--accent) 18%, var(--surface) 82%)",
  '--md-comp-button-tonal-on-container': '#003A73',
  '--md-comp-button-tonal-container-hover': "color-mix(in srgb, var(--md-comp-button-tonal-container) 90%, #003A73 10%)",
  '--md-comp-button-elevated-container': 'rgba(255, 255, 255, 0.94)',
  '--md-comp-button-elevated-on-container': '#1D1D1F',
  '--md-comp-button-elevated-container-hover': 'rgba(255, 255, 255, 0.98)',
  '--md-comp-button-outlined-outline': 'rgba(60, 60, 67, 0.26)',
  '--md-comp-button-outlined-hover-layer': 'rgba(10, 132, 255, 0.12)',
  '--md-comp-button-text-label': '#0A84FF',
  '--md-comp-button-text-hover-layer': 'rgba(10, 132, 255, 0.12)',
  '--md-comp-button-ghost-label': 'rgba(60, 60, 67, 0.72)',
  '--md-comp-button-ghost-hover-layer': 'rgba(60, 60, 67, 0.08)',
  '--md-comp-button-danger-container': '#FF3B30',
  '--md-comp-button-danger-on-container': '#FFFFFF',
  '--md-comp-button-danger-container-hover': "color-mix(in srgb, #FF3B30 92%, #FFFFFF 8%)",
  '--md-comp-button-success-container': '#34C759',
  '--md-comp-button-success-on-container': '#FFFFFF',
  '--md-comp-button-success-container-hover': "color-mix(in srgb, #34C759 92%, #FFFFFF 8%)",
  '--md-comp-focus-ring': 'rgba(10, 132, 255, 0.6)',

  '--md-comp-field-container': 'rgba(255, 255, 255, 0.66)',
  '--md-comp-field-outline': 'rgba(60, 60, 67, 0.26)',
  '--md-comp-field-on-surface': '#1D1D1F',
  '--md-comp-field-placeholder': 'rgba(60, 60, 67, 0.48)'
} as const satisfies ThemeVariableRecord

const appleMidnightVars = {
  ...appleSkyVars,
  '--md-sys-color-primary': '#409CFF',
  '--md-sys-color-on-primary': '#001F3F',
  '--md-sys-color-primary-container': '#003A73',
  '--md-sys-color-on-primary-container': '#D6EBFF',
  '--md-sys-color-secondary': '#64D2FF',
  '--md-sys-color-on-secondary': '#002738',
  '--md-sys-color-secondary-container': '#00324F',
  '--md-sys-color-on-secondary-container': '#C6F2FF',
  '--md-sys-color-tertiary': '#32D74B',
  '--md-sys-color-on-tertiary': '#003A16',
  '--md-sys-color-tertiary-container': '#005223',
  '--md-sys-color-on-tertiary-container': '#A7F5B6',
  '--md-sys-color-background': '#1C1C1E',
  '--md-sys-color-on-background': '#F2F2F7',
  '--md-sys-color-surface': '#2C2C2E',
  '--md-sys-color-on-surface': '#F2F2F7',
  '--md-sys-color-surface-variant': 'rgba(235, 235, 245, 0.16)',
  '--md-sys-color-on-surface-variant': 'rgba(235, 235, 245, 0.65)',
  '--md-sys-color-outline': 'rgba(99, 99, 102, 0.5)',
  '--md-sys-color-outline-variant': 'rgba(99, 99, 102, 0.32)',
  '--md-sys-color-shadow': 'rgba(0, 0, 0, 0.6)',
  '--md-sys-color-scrim': 'rgba(0, 0, 0, 0.7)',
  '--md-sys-color-surface-tint': '#409CFF',
  '--md-sys-color-inverse-surface': '#F5F5F7',
  '--md-sys-color-inverse-on-surface': '#1D1D1F',
  '--md-sys-color-inverse-primary': '#66B7FF',
  '--md-sys-color-surface-container-lowest': '#000000',
  '--md-sys-color-surface-container-low': '#1C1C1E',
  '--md-sys-color-surface-container': '#1F1F21',
  '--md-sys-color-surface-container-high': '#262628',
  '--md-sys-color-surface-container-highest': '#2F2F31',
  '--md-sys-color-error': '#FF453A',
  '--md-sys-color-on-error': '#220002',
  '--md-sys-color-error-container': '#8A1410',
  '--md-sys-color-on-error-container': '#FFDAD4',
  '--md-sys-color-success': '#30D158',
  '--md-sys-color-on-success': '#002B12',
  '--md-sys-color-success-container': '#0F5227',
  '--md-sys-color-on-success-container': '#A8F2BC',

  '--bg': '#1C1C1E',
  '--fg': '#F2F2F7',
  '--muted': 'rgba(235, 235, 245, 0.65)',
  '--link': '#66B7FF',
  '--surface': '#2C2C2E',
  '--surface-2': '#1F1F21',
  '--surface-panel': '#262628',
  '--surface-veil': 'rgba(64, 156, 255, 0.12)',
  '--surface-translucent': 'rgba(44, 44, 46, 0.78)',
  '--border': 'rgba(84, 84, 88, 0.42)',
  '--border-soft': 'rgba(84, 84, 88, 0.32)',
  '--border-muted': 'rgba(84, 84, 88, 0.22)',
  '--border-strong': 'rgba(84, 84, 88, 0.52)',
  '--accent': '#409CFF',
  '--accent-weak': 'rgba(64, 156, 255, 0.26)',
  '--accent-strong': '#003A73',
  '--enemy-accent': '#FF375F',
  '--env-accent': '#32D74B',
  '--danger-soft': 'rgba(255, 69, 58, 0.22)',
  '--success-soft': 'rgba(50, 215, 75, 0.22)',
  '--danger-border': 'rgba(255, 69, 58, 0.42)',
  '--success-border': 'rgba(50, 215, 75, 0.42)',
  '--overlay': 'rgba(0, 0, 0, 0.5)',
  '--gridline': 'rgba(99, 99, 102, 0.24)',

  '--shadow-level1': '0 18px 34px rgba(5, 5, 10, 0.42)',
  '--shadow-level2': '0 24px 52px rgba(5, 5, 10, 0.46)',
  '--shadow-level3': '0 32px 64px rgba(5, 5, 10, 0.52)',
  '--shadow-level4': '0 42px 82px rgba(5, 5, 10, 0.58)',
  '--shadow-level5': '0 56px 96px rgba(5, 5, 10, 0.64)',
  '--shadow-elevated': '0 28px 60px rgba(5, 5, 10, 0.5)',

  '--md-comp-button-filled-container': 'var(--accent)',
  '--md-comp-button-filled-on-container': '#001F3F',
  '--md-comp-button-filled-container-hover': "color-mix(in srgb, var(--accent) 88%, #001F3F 12%)",
  '--md-comp-button-tonal-container': 'rgba(64, 156, 255, 0.22)',
  '--md-comp-button-tonal-on-container': '#D6EBFF',
  '--md-comp-button-tonal-container-hover': "color-mix(in srgb, rgba(64, 156, 255, 0.22) 88%, #66B7FF 12%)",
  '--md-comp-button-elevated-container': 'rgba(44, 44, 46, 0.92)',
  '--md-comp-button-elevated-on-container': '#F2F2F7',
  '--md-comp-button-elevated-container-hover': 'rgba(44, 44, 46, 0.96)',
  '--md-comp-button-outlined-outline': 'rgba(120, 120, 128, 0.45)',
  '--md-comp-button-outlined-hover-layer': 'rgba(64, 156, 255, 0.16)',
  '--md-comp-button-text-label': '#66B7FF',
  '--md-comp-button-text-hover-layer': 'rgba(102, 183, 255, 0.16)',
  '--md-comp-button-ghost-label': 'rgba(235, 235, 245, 0.7)',
  '--md-comp-button-ghost-hover-layer': 'rgba(235, 235, 245, 0.14)',
  '--md-comp-button-danger-container': '#FF453A',
  '--md-comp-button-danger-on-container': '#220002',
  '--md-comp-button-danger-container-hover': "color-mix(in srgb, #FF453A 88%, #220002 12%)",
  '--md-comp-button-success-container': '#30D158',
  '--md-comp-button-success-on-container': '#002B12',
  '--md-comp-button-success-container-hover': "color-mix(in srgb, #30D158 88%, #002B12 12%)",
  '--md-comp-focus-ring': '#66B7FF',

  '--md-comp-field-container': 'rgba(44, 44, 46, 0.84)',
  '--md-comp-field-outline': 'rgba(120, 120, 128, 0.45)',
  '--md-comp-field-on-surface': '#F2F2F7',
  '--md-comp-field-placeholder': 'rgba(235, 235, 245, 0.55)'
} as const satisfies ThemeVariableRecord

export const themeVariables = {
  'material-aurora': materialAuroraVars,
  'material-midnight': materialMidnightVars,
  'apple-sky': appleSkyVars,
  'apple-midnight': appleMidnightVars
} as const

export type ThemeName = keyof typeof themeVariables
export type ThemeVariables = (typeof themeVariables)[ThemeName]
export type ThemeVariableName = keyof ThemeVariables

export const themeOrder: ThemeName[] = ['material-aurora', 'material-midnight', 'apple-sky', 'apple-midnight']

export const defaultThemeName: ThemeName = 'material-aurora'

export const themeMeta: Record<ThemeName, { label: string; description: string; accent: string; family: 'material' | 'apple'; mode: 'light' | 'dark' }> = {
  'material-aurora': {
    label: 'Material Aurora',
    description: 'Soft lilac primaries, luminous surfaces, and expressive depth inspired by Material You.',
    accent: '#6750A4',
    family: 'material',
    mode: 'light'
  },
  'material-midnight': {
    label: 'Material Midnight',
    description: 'Moody dark tones with radiant lilac and blush highlights from Material Design 3.',
    accent: '#D0BCFF',
    family: 'material',
    mode: 'dark'
  },
  'apple-sky': {
    label: 'Apple Sky',
    description: 'Airy translucency, vibrant blues, and crisp contrast styled after modern Apple interfaces.',
    accent: '#0A84FF',
    family: 'apple',
    mode: 'light'
  },
  'apple-midnight': {
    label: 'Apple Midnight',
    description: 'High-contrast typography and luminous color pops inspired by Apple’s dark appearance.',
    accent: '#409CFF',
    family: 'apple',
    mode: 'dark'
  }
}

export function isThemeName(value: string): value is ThemeName {
  return themeOrder.includes(value as ThemeName)
}

export const themeVariablesList: ThemeVariableName[] = Object.keys(themeVariables[defaultThemeName]) as ThemeVariableName[]
